# Site settings
title: WalterDDR
header-img: img/home-bg.jpg
email: walterddr.walterddr@gmail.com
copyright_name: walterddr 
description: "WalterDDR"
baseurl: ""
url: "http://walterddr.github.io"
twitter_username: walterddr
github_username: walterddr 
facebook_username:  

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
